title: "Windsboro HOA"
slogan: ""
description: "Windsboro HOA Website"
destination: docs

author: anelson425

url: 'https://www.windsboro.org'
baseurl: ''
css_url: 'https://www.windsboro.org'

improve_content: https://github.com/Phlow/feeling-responsive/edit/gh-pages

urlimg: 'https://www.windsboro.org/images/'

markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
plugins: [jekyll-paginate]
excerpt_separator: "<!--more-->"
include: ['.htaccess']

exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md


language: "en"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: anelson425     # Default author for pages
sass:
    sass_dir: _sass
    style: :compressed

google_analytics_tracking_id: UA-139748334-1
