locale: en-US
title: Windsboro HOA
theme: hoa
disableKinds: [taxonomy, term]
params:
  masthead: images/windsboro_masthead.jpg
  payhoa_url: https://app.payhoa.com/auth/join/20117-windsboro
  # Update these each year when new dues are set
  dues_amount: "$799"
  dues_year: "2026"
copyright: Windsboro HOA
markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
baseURL: 'https://www.windsboro.org'
