baseURL: 'https://www.windsboro.org'
languageCode: en-us
title: Windsboro HOA
theme: hoa
params:
  masthead: images/windsboro_masthead.jpg
menu:
  main:
    - name: Links
      url: /links
    - name: Documents
      url: /documents
    - name: Contacts
      url: /contacts
    - name: Pool
      url: /pool
    - name: Ponds
      url: /ponds
    - name: Gallery
      url: /gallery
    - name: HOA Dues
      url: /hoa_dues
    - name: Calendar
      url: /calendar
copyright: Windsboro HOA
markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
google_analytics_tracking_id: UA-139748334-1
